### ISSUE TITLE
My new update of OptEco will not support AccountLoader class

### ISSUE THREAD

**Issue by PlayerNguyen** [BetterGUI-MC/OptEcoBridge#4]
Dear @HSGamer , my plugin OptEco in 1.15b (will be release) will not support AccountLoader anymore, please using [this OptEcoAPI](https://github.com/PlayerNguyen/OptEco/blob/master/src/main/java/me/playernguyen/opteco/api/OptEcoAPI.java) instead of. It's more easy and stable than AccountLoader cus I designed this class for the API usage. 
Gratefully for supporting and using my plugin. Thanks!

**Comment by HSGamer** [comment]
It could be a waste of objects.
But okay, I will update my addon soon.
